import { Interrupt } from "@langchain/langgraph-sdk";

/**
 * Interface for the clarifying question interrupt schema.
 * Generated by the ask_clarifying_question tool in the backend.
 */
export interface ClarifyingQuestionInterrupt {
  field_name: string;
  question: string;
  option_1: string;
  option_2: string;
  option_3: string;
  option_4: string;
}

/**
 * Type guard to check if an interrupt value is a ClarifyingQuestionInterrupt.
 * Validates the presence and type of all required fields.
 */
export function isClarifyingQuestionInterrupt(
  value: unknown
): value is Interrupt<ClarifyingQuestionInterrupt> {
  if (!value || typeof value !== "object") {
    return false;
  }

  // Handle both single interrupt and array of interrupts
  const interruptValue = Array.isArray(value)
    ? (value[0] as Interrupt<ClarifyingQuestionInterrupt>)?.value
    : (value as Interrupt<ClarifyingQuestionInterrupt>)?.value;

  if (!interruptValue || typeof interruptValue !== "object") {
    return false;
  }

  const interrupt = interruptValue as Partial<ClarifyingQuestionInterrupt>;

  // Check all required fields exist and are strings
  const requiredFields = [
    "field_name",
    "question",
    "option_1",
    "option_2",
    "option_3",
    "option_4",
  ] as const;

  return requiredFields.every(
    (field) =>
      field in interrupt &&
      typeof interrupt[field] === "string" &&
      interrupt[field]!.length > 0
  );
}

/**
 * Extract the ClarifyingQuestionInterrupt value from an Interrupt object.
 */
export function getClarifyingQuestionValue(
  interrupt: unknown
): ClarifyingQuestionInterrupt | null {
  if (!isClarifyingQuestionInterrupt(interrupt)) {
    return null;
  }

  const interruptObj = Array.isArray(interrupt) ? interrupt[0] : interrupt;
  return (interruptObj as Interrupt<ClarifyingQuestionInterrupt>).value ?? null;
}

/**
 * Extract the full interrupt object for clarifying question.
 * This is needed to access the interrupt ID for resuming multiple interrupts.
 */
export function getClarifyingQuestionInterrupt(
  interrupt: unknown
): Interrupt<ClarifyingQuestionInterrupt> | null {
  if (!isClarifyingQuestionInterrupt(interrupt)) {
    return null;
  }

  const interruptObj = Array.isArray(interrupt) ? interrupt[0] : interrupt;
  return interruptObj as Interrupt<ClarifyingQuestionInterrupt>;
}
